### PR TITLE
Add Aeron.Driver.Native project

### PR DESCRIPTION
**Pull request by buybackoff**
Hello!

These are the native parts of what we published as https://github.com/Abc-Arbitrage/Aeron.MediaDriver.NET

We discussed this with @JPWatson and came up with this:

>  I could create a PR with only the native parts.
\>Sounds good.

>  One thing to discuss is how do we pack binaries and do we commit them? 
\>Simplest to commit initially.

> We do want that the first published 0.1.0 version (or we could find which version it was at the last commit by @ltrzesniewski) has exactly the same binaries that we've committed (because we trust them). After that bootstrap step, the binaries and the NuGet version could be put in sync with the upstream version.
\>That's fine, it's in-line based off 1.21.2? So we can publish 1.21.2-alpha or something to that effect?

The actual version of the included binaries was before [`1.26`](https://github.com/real-logic/aeron/releases/tag/1.26.0), so the initial NuGet version is `1.26.0-beta`. The Windows binary works without major issues, only [a minor issue](https://github.com/real-logic/aeron/issues/1108) is detected so far.

We have agreed to publish these binaries with `-beta` flag so that our current usage could be migrated to a new NuGet without risks of breakage from updated version, but then we will sync the binaries with the current version of the native driver, hopefully via CI (GitHub Actions).

### CODE REVIEW

**Comment by buybackoff** [comment]
The issue on mono seems to be causes by an old version of MSBuild.

I'm curious if supporting `net45` and `necoreapp2.0` is still required when .NET 5 is RTM? Shouldn't `netstandard2.0` be enough? It works without issues with full .NET starting from 4.7.2. And then maybe multitarget to .NET 5 or 3.1 LTS, but that's probably not needed unless any feature from .NET Core 3+ is used.

Also, how about GitHub Actions? Waiting 30 mins for Travis just to start is too much.

**Comment by buybackoff** [comment]
Old binaries are no longer needed, we could bootstrap using a local NuGet feed. So will update to all new driver configs and clean up things.

**Comment by buybackoff** [comment]
I have reworked the `Aeron.Driver.Native` implementation to follow the design of `Aeron.Client`. This is how it should have been implemented in the first place. It requires access to some internals inside `Aeron` class, but I see no problem in this. 

I do not fully understand the CI issue and how to update the version used. In `.travis.yml` it's specified as the latest, but there is a path override to use the version `4.5` for build. Could we update `4.5` to `4.7.2` (lowest .NET Standard 2 that works) or even `4.8.x`? Or just leave `netstandard2.0` only, that will be ok for `4.7.2+` clients.

**Comment by JPWatson** [comment]
As suggested, I've enabled GitHub actions, turned off travis and appveyor and removed support for `net45`. Have been playing around with a branch [here](https://github.com/AdaptiveConsulting/Aeron.NET/tree/native_driver_test) to get things up and running.

A couple of issues that have come up:
- SharpGenTools.Sdk throws a MethodMissingException on latest version of SDK (issue is [here](https://github.com/SharpGenTools/SharpGenTools/issues/164) so I've pegged the SDK version to 3.1.101 for now.
- I had to build the .so library on my side (because of a different version of GLIBC). Not sure the best way to compile that and make it reproducible going forward.
- I increased the driver timeout from 1s to 10s (not sure whether than was intentional or not).

The main blocking issue at the moment is that something funky is going on with the Windows tests, seems to take a while to emit the config debug to STDOUT and is ultimately timing out. I'm not sure what's going on there. Turning off the debug output allows the test to run but I think there is some fundamental problem there. There may be some parallelism or leaked resource that is overwhelming the container.

```
2020-12-27T23:09:39.1767244Z aeron_driver_context_t {
2020-12-27T23:09:39.1767950Z     cnc_version=0.2.0
2020-12-27T23:09:39.1769251Z     aeron_dir=D:\a\Aeron.NET\Aeron.NET\src\Adaptive.Aeron.Driver.Native.Tests\bin\Debug\netcoreapp3.1\mediadrivers\a5f70cf35e5543b490bb89b420a3365e
2020-12-27T23:09:39.1770684Z     driver_timeout_ms=10000
2020-12-27T23:09:39.1771362Z     print_configuration_on_start=1
2020-12-27T23:09:39.1771936Z     dirs_delete_on_start=1
2020-12-27T23:09:39.1772456Z     dirs_delete_on_shutdown=1
2020-12-27T23:09:39.1772988Z     warn_if_dirs_exists=0
2020-12-27T23:09:39.1773501Z     term_buffer_sparse_file=0
2020-12-27T23:09:39.1774063Z     perform_storage_checks=1
2020-12-27T23:09:39.1774796Z     spies_simulate_connection=0
2020-12-27T23:09:39.1775530Z     reliable_stream=1
2020-12-27T23:09:39.1776069Z     tether_subscriptions=1
2020-12-27T23:09:39.1776606Z     rejoin_stream=1
2020-12-27T23:09:39.1777155Z     receiver_group_consideration=2
2020-12-27T23:09:50.1961596Z     to_driver_buffer_length=1049344
2020-12-27T23:10:00.8840787Z     to_clients_buffer_length=1048704
2020-12-27T23:10:13.9454035Z     counters_values_buffer_length=1048576
2020-12-27T23:10:23.4436912Z     error_buffer_length=1048576
2020-12-27T23:10:36.5063234Z     timer_interval_ns=1000000000
2020-12-27T23:10:59.0692962Z     client_liveness_timeout_ns=10000000000
2020-12-27T23:11:12.1337851Z     image_liveness_timeout_ns=10000000000
2020-12-27T23:11:15.6959392Z     publicat  √ CouldReusePort [707ms]
2020-12-27T23:11:28.7596669Z ion_unblock_timeout_ns=15000000001
2020-12-27T23:11:39.4467566Z     publication_connection_timeout_ns=5000000000
2020-12-27T23:11:50.1351538Z     publication_linger_timeout_ns=5000000000
2020-12-27T23:11:55.8231016Z     untethered_window_limit_timeout_ns=5000000000
2020-12-27T23:11:55.8260358Z     untethered_resting_timeout_ns=10000000000
2020-12-27T23:12:15.0722695Z     retransmit_unicast_delay_ns=0
2020-12-27T23:12:23.3852502Z     retransmit_unicast_linger_ns=60000000
2020-12-27T23:12:37.3783665Z     nak_unicast_delay_ns=60000000
```


In terms of design, I'm not sure about the two-in-one Aeron client + Driver. My instinct would be to keep things as separate as possible. In the Java variant, they share a CommonContext with stuff like `aeronDirectoryName`.
Also wondering whether we should construct a Context that delegates straight to the C++ interop to remove some of that code.

**Comment by buybackoff** [comment]
> Turning off the debug output allows the test to run but I think there is some fundamental problem there.

Could we just skip this functionality for the initial release? I added logger functions to driver config because the stdout is sometimes useless, such as in out case with a custom logging. I couldn't find a way top plug in a custom logger function to PrintConfigurationOnStart (maybe just missed). We could print manually to the logger function all the parameters that .NET binding supports, probably guarded by the same config option.

> In terms of design, I'm not sure about the two-in-one Aeron client + Driver. My instinct would be to keep things as separate as possible.

It was separate in the initial version, but I found the initial version inconvenient. But that was mostly due to the config.

>  In the Java variant, they share a CommonContext with stuff like aeronDirectoryName.

I viewed the embedded driver as an optional extension, without any attempt to replicate Java design or modify the client code in any way. Ideally, I wanted to have zero changes to the client. With the decoupled driver that should be possible.

**Comment by JPWatson** [comment]
> Could we just skip this functionality for the initial release? 

Even with the debug output turned off, the later tests still seems slower so I wonder whether there's a resource leak. I was planning on running the tests on my Windows machine but haven't got round to it yet.

> It was separate in the initial version, but I found the initial version inconvenient. 

Just to make sure, you're happy with them separated?

> I regret using SharpGenTools, the tool looks unstable and abandoned. 

I had a quick look around for other options but couldn't find any. Are you aware of any others?

**Comment by buybackoff** [comment]
> Just to make sure, you're happy with them separated?

I'm happy with keeping the driver and the client separate.

But I really liked the design of the DriverContext just extending the client context and reusing it's shared properties to avoid duplication. I see you've removed that. Also DebugTimeout thing is very handy, I had to do similar thing initially.

> I had a quick look around for other options but couldn't find any. Are you aware of any others?

There is [CppSharp](https://github.com/mono/CppSharp), but not an out-of-the-box NuGet with declarative config. It's more powerful but requires more work ([sample](https://github.com/Spreads/Spreads.BLAS/blob/master/tools/BindGen/Program.cs)) and an explicit build step (which could probably be automated with MSBuild, but that is even more work).

> Even with the debug output turned off, the later tests still seems slower so I wonder whether there's a resource leak. I was planning on running the tests on my Windows machine but haven't got round to it yet.

Did you run this on CI machine? Are the number of cores > number of spinning threads on the machine?

**Comment by buybackoff** [comment]
> I regret using SharpGenTools, the tool looks unstable and abandoned.

Another option is just to copy the generated source, commit it, and get rid of SharpGenTools. Later maintain it manually for new APIs, the number of which should be small.

**Comment by JPWatson** [comment]
> Did you run this on CI machine? Are the number of cores > number of spinning threads on the machine?

Yeah running on GitHub [here](https://github.com/AdaptiveConsulting/Aeron.NET/runs/1615423605).  There shouldn't be any spinning threads.

**Comment by JPWatson** [comment]
> But I really liked the design of the DriverContext just extending the client context and reusing it's shared properties to avoid

I think the only shared properties are:
- aeron directory name
- driver timeout

> Also DebugTimeout thing is very handy

Will look into that a bit more.

**Comment by buybackoff** [comment]
I agree that the number of shared props is small. Could we just copy the debug timeout logic as well?

What do you think about just committing the generated code? And about statically linking `msvcrt/libc`?

**Comment by JPWatson** [comment]
> What do you think about just committing the generated code?

Fine with that, that's what we do for the SBE generation.

> And about statically linking msvcrt/libc?

Whatever we do here, it's going to not work for someone. Think we should make it easy to override the bundled library easily so people can adapt to their particular deployment + some docs to describe how to do it.

**Comment by buybackoff** [comment]
Hello! I've force pushed here, starting from the `native_driver_test` branch. It may be easier to create a PR (maybe temporary) for that branch to see the diff in a more convenient way.

**Comment by buybackoff** [comment]
It looks like slow tests on Linux were fixed in the last commit, it failed very fast. The failing test is the one that should not run at all 
image

**Comment by buybackoff** [comment]
I've disabled `PrintConfigurationOnStart`. On my Windows machine with 8 cores it works fine with 16 drivers when the setting is enabled. So it's probably some CI output weirdness.

**Pull request closed without merging**
