### PR TITLE
Remove duplicate memory barrier

### PR DESCRIPTION
**Pull request by buybackoff**
PutLongOrdered uses Volatile.Write that already generates an implicit memory barrier, no need for Thread.MemoryBarrier() after it. http://stackoverflow.com/a/6932271/801189

Note that we keep one fence as opposed to my initial comment in #29 to remove both. @mjpt777 then explained that "The fence ordering is important to detection of dead clients that have written a partial message." But performance gain is still around 15-20%. @JPWatson already had a comment on that line about that and he was definitely right, this should be removed.

### CODE REVIEW

**Comment by mjpt777** [comment]
Is there a StoreStore fence after the write to ensure the other header fields do not float before write of the length? A "release" write tends to have a release fence before it then the write with no fence after it.

**Comment by JPWatson** [comment]
Technically, I think we could get away without it for the CLR
image
http://www.albahari.com/threading/part4.aspx
but the ECMA spec has weaker guarantees so I think it's probably worth keeping.

**Comment by JPWatson** [comment]
As a hack, could we do something like this?
Volatile.Write(ref *(long*)(_pBuffer + index), value);
Volatile.Write(ref *(long*)(_pBuffer + index), value);

Doing Volatile.Write means that we have a release fence before and after the write and we also get the performance boost.

**Comment by mjpt777** [comment]
If the volatile writes retain total store order, which is suggested in your link, then this should be fine.

**Comment by buybackoff** [comment]
Finally I understand why it may be needed. If a writer dies right after writing the negative length, then unblocker could see the value and unblock. Then the questions are:
* what happens if the writer dies before the line `Thread.MemoryBarrier();` but after `termBuffer.PutLongOrdered`
* shouldn't term unblocker use a fence before reading, since it happens only on onTime event which is less frequent that writes? Before [this line](https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/java/io/aeron/logbuffer/TermUnblocker.java#L73). 

But without digging deeper, in the last commit there is a trick: adding another `PutLongOrdered` after the first one increases performance in almost the same way as just removing the memory barrier, but guarantees that the length is always written before other fields.

**Comment by buybackoff** [comment]
@JPWatson haven't noticed your comment about double volatile while writing my comment and actually trying that hack, but yes, that hack works :)

**Comment by mjpt777** [comment]
> what happens if the writer dies before the line Thread.MemoryBarrier(); but after termBuffer.PutLongOrdered

This is fine. The barrier is for the compiler to ensure negative length is written first. On x86 the barriers/fences are for the compiler and not the hardware in this case.

The ordered write is effectively a StoreStore barrier followed by a atomic write of the value.

> shouldn't term unblocker use a fence before reading, since it happens only on onTime event which is less frequent that writes? Before this line.

The unblocker is doing an acquire operation when it reads.

**Comment by mjpt777** [comment]
I've been thinking about this and reviewing the unblocker. We don't need any ordered writes until the length is flipped to positive. If .NET can atomically write the length negative then it does not matter about order.

**Comment by mjpt777** [comment]
Forgot that. Long week. The first write could be elided by a smart compiler.

**Comment by buybackoff** [comment]
Changing both to simple PutLong doesn't increase performance substantially (or at all). Likely because on x64 architecture .NET all writes are already implemented as ordered.

> As it happens, Intel’s X86 and X64 processors always apply acquire-fences to reads and release-fences to writes (from [here](http://www.albahari.com/threading/part4.aspx))

**Comment by omariom** [comment]
@mjpt777 
>Is there a StoreStore fence after the write to ensure the other header fields do not float before write of the length? A "release" write tends to have a release fence before it then the write with no fence after it.

With the change write to `DataHeader.STREAM_ID` can float before both `DataHeader.TERM_OFFSET` and `Header.FRAME_LENGTH`.
Is that ok?

**Comment by JPWatson** [comment]
@omariom I don't think that's the case.
I think in theory the write to STREAM_ID can float before the write to TERM_OFFSET but not before FRAME_LENGTH.
The [Java code ](https://github.com/real-logic/Aeron/blob/master/aeron-client/src/main/java/io/aeron/logbuffer/HeaderWriter.java#L87) has a store fence which is what Volatile.Write is doing in C#, see [here](
http://blog.alexrp.com/2014/03/30/dot-net-atomics-and-memory-model-semantics/
).

**Comment by omariom** [comment]
@JPWatson 
If normal write to STREAM_ID can be reordered with previous  store-release (volatile write) to TERM_OFFSET 
it can consequently be reordered with another store-release before it.

**Comment by JPWatson** [comment]
My understanding is that logically, you end up with something like this:

```
store-rel barrier
FRAME_LENGTH = 9
store-rel barrier
TERM_OFFSET = 2
STREAM_ID = 43
```

Where neither STREAM_ID nor TERM_OFFSET can move above the 2nd barrier.

**Comment by omariom** [comment]
This an exempt for ECMA C# spec:
>• A write of a volatile field is called a volatile write. A volatile write has “release semantics”; that is, it is guaranteed to happen after any memory references prior to the write instruction in the instruction sequence.

**Comment by JPWatson** [comment]
It's call to Volatile.Write rather than a write to a volatile field. Here's the MSDN documentation:

Writes a value to a field. On systems that require it, **inserts a memory barrier that prevents the processor from reordering memory operations as follows: If a read or write appears before this method in the code, the processor cannot move it after this method.**
https://msdn.microsoft.com/en-us/library/system.threading.volatile.write(v=vs.110).aspx

**Comment by omariom** [comment]
Volatile reads and writes are always reads/writes from/to  memory locations and implemented with `.volatile` prefix to some IL instructions. Both C# volatile fields and methods of `Volatile` class  use  them.

I will try to explain with an example.
Imagine these writes and reads:
```C#
//Some writes and reads prior to volatile writes
var la = _a;
var _b = 3;

Volatile.Write(ref _frameLength, <some value>);
Volatile.Write(ref _termOffset, <some value>);
_streamId = <some value>
```
First  4 reads and writes can float **after** write to `_streamId ` and it will preserve semantics of `volatile write` from ECMA C# spec:

```C#
_streamId = <some value>

//Some write and reads prior to volatile writes
var la = _a;
var _b = 3;

Volatile.Write(ref _frameLength, <some value>);
Volatile.Write(ref _termOffset, <some value>);
```

**Comment by omariom** [comment]
@JPWatson 
>Doing Volatile.Write means that we have a release fence before and after the write.

That's the tricky part!  Volatile write in .NET is not a release fence, it is a store-release. Release fence prevents reordering of reads and writes that appear before the fence  with writes following it. .NET's volatile write (store-release) only prevents reordering of prior reads/writes with itself.

**Comment by mjpt777** [comment]
The order of writes to the other headers does not matter for the unblocking algorithm. For Aeron to work correctly the two writes to the header length cannot be reordered with each other. The really important part is that the body of the message is written between these two length writes.

**Comment by JPWatson** [comment]
@omariom hmm I think the guarantee is stronger on platforms that would do that kind of reordering.
> Volatile.Write inserts a memory barrier on systems that require it.

**Comment by omariom** [comment]
@JPWatson 
This is what a member of the TPL and Parallel LINQ teams says:
> When writing CPU-intensive code, it sometimes makes sense to use volatile fields, as long as you only rely on the ECMA C# specification guarantees and not on architecture-specific implementation details.

https://msdn.microsoft.com/en-us/magazine/jj863136
https://msdn.microsoft.com/en-us/magazine/jj883956

**Comment by omariom** [comment]
@mjpt777 @JPWatson 
> For Aeron to work correctly the two writes to the header length cannot be reordered with each other. The really important part is that the body of the message is written between these two length writes.

Then I believe the removed explicit full memory barrier required there.
```
first write to length (volatile)
message body  write   // can float above  first length write            
final write to length (volatile)
```

**Comment by JPWatson** [comment]
@omariom Assuming Volatile.Write won't add in a full memory barrier on platforms with weaker memory models, do you think if you add a dummy Volatile.Read would be enough to prevent the unwanted floating?
```
first write to length (volatile)
read length (volatile)
message body  write   // can no longer float above  first length write            
final write to length (volatile)
```

**Comment by omariom** [comment]
@JPWatson
That was [the question I asked on SO](http://stackoverflow.com/questions/16572571/memory-model-preventing-store-release-and-load-acquire-reordering) :) and later found [the answer](http://stackoverflow.com/a/32760918/2387098).

**Comment by JPWatson** [comment]
It's not exactly the same question, your SO overflow question deals with read being reordered with a write where this is all writes.

If we're going we the ECMA spec:

> * A write of a volatile field is called a volatile write. A volatile write has “release semantics”; that is, it is guaranteed to happen after any memory references prior to the write instruction in the instruction sequence.
> * A read of a volatile field is called a volatile read. A volatile read has “acquire semantics”; that is, it is guaranteed to occur prior to any references to memory that occur after it in the instruction sequence.
> These restrictions ensure that all threads will observe volatile writes performed by any other thread in the order in which they were performed.

If we use Brian Gideon's arrow notation where
>  I use an up arrow ↑ and a down arrow ↓ to represent volatile writes and reads respectively. Think of the arrow head as pushing away any other reads or writes. So no other memory access can move past the arrow head, but they can move past the tail.

Then we end up here:
```
↑          
first write to length (volatile)
read length (volatile)
↓
message body write
↑
final write to length (volatile)
```
which seems acceptable.

I don't think the counterexample in Joe Duffy's articles is relevant because we're only writing so store buffer forwarding is not a concern.

**Comment by omariom** [comment]
@JPWatson  Hmm.. now I am not sure..
We can think this way:
If it were only on .NET level then that dummy read would be enough, right? 
But thanks to store-buffer forwarding
```
X = 1
r0 = X;
r1 = Y
```
becomes
```
r0 = 1
X = r0
r1 = Y
```
and read `r1 = Y` can bypass write `X = r0` on x86-x64.

But if it were a write to `Y` then on x86 - where writes **can't** bypass other writes -..
```
X = 1
r0 = X
Y = 2
```
becomes..
```
r0 = 1
X = r0
Y = 2
```
.. 'Y = 2' still happens after 'X = r0'.

Looks like  you are right.

And that's an interesting question by itself! I will ask it  on .NET Core CLR repo.

**Pull request merged**
