### PR TITLE
Use UnsafeBuffer & remove virtual methods

### PR DESCRIPTION
**Pull request by JPWatson**
Tests still run in debug mode using compiler directives.

On my machine IPC throughput goes from 22 to 38 million msg/sec.

Won't merge yet, will leave for discussion.

### CODE REVIEW

**Comment by JPWatson** [comment]
seems to me that the increase in performance justifies compromising the codebase with #ifs and as there are no semantic changes, I don't think it would have a negative impact on future porting effects. 
would be interested to hear your thoughts @buybackoff & @odeheurles

**Comment by buybackoff** [comment]
Cool. I thought that #ifs are terrible to maintain. If you want to go this path, this is the simplest from jit pov.

**Comment by odeheurles** [comment]
I do not think it is that bad from a maintainability point of view, I can't think of anything simpler tbh..

Happy to get this merged

Olivier

**Comment by buybackoff** [comment]
+1. 38Mops!? What is your hardware? How this compares to Java on the same machine? I am still somewhat envious to that numbers and am biased for .NET :)

**Pull request merged**
